Project/project03/19-05/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

Project/project03/19-05/blog/blogs/urls.py
"""Define URL patterns for blogs."""

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # home page
    path('', views.index, name='index'),
    # add a new blog post
    path('new_post/', views.new_post, name='new_post'),
    # edit blog post page
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

Project/project03/19-05/blog/users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # reuse django default auth urls with base template
    path('', include('django.contrib.auth.urls')),
    # register page
    path('register/', views.register, name='register'),
]

Project/project03/19-05/blog/blogs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class BlogPost(models.Model):
    """A post the user made on his blog."""
    title = models.CharField(max_length=80)
    text = models.TextField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

Project/project03/19-05/blog/users/models.py
from django.db import models

# Create your models here.

Project/project03/19-05/blog/blogs/forms.py
from django import forms

from .models import BlogPost


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['text']
        labels = {'text': ''}

Project/project03/19-05/blog/blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost
from .forms import BlogPostForm

# Create your views here.


def __check_blogpost_owner(_blogpost, _request):
    if _blogpost.owner != _request.user:
        raise Http404


def index(request):
    """The home page for blogs."""
    # noinspection PyUnresolvedReferences
    my_posts = BlogPost.objects.order_by('date_added')
    context = {'blog_posts': my_posts}
    return render(request, 'blogs/index.html', context)


@login_required
def new_post(request):
    """Add a new blog post."""
    if request.method != 'POST':
        # create a blank form
        form = BlogPostForm()
    else:
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            my_new_post = form.save(commit=False)
            my_new_post.owner = request.user
            my_new_post.save()
            return redirect('blogs:index')

    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)


@login_required
def edit_post(request, post_id):
    """Edit an existing blog post."""
    # noinspection PyUnresolvedReferences
    my_post = BlogPost.objects.get(id=post_id)
    __check_blogpost_owner(my_post, request)
    if request.method != 'POST':
        # pre-fill form with my_post
        my_form = BlogPostForm(instance=my_post)
    else:
        # save edited blog post
        my_form = BlogPostForm(instance=my_post, data=request.POST)
        if my_form.is_valid():
            my_form.save()
            return redirect('blogs:index')

    context = {'post': my_post, 'form': my_form}
    return render(request, 'blogs/edit_post.html', context)

Project/project03/19-05/blog/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process filled form.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('blogs:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

Project/project03/19-05/blog/blogs/templates/blogs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
  <p>
    <a href="{% url 'blogs:index' %}">My Blog</a> -
    {% if user.is_authenticated %}
      {{ user.username }} -
      <a href="{% url 'users:logout' %}">Logout</a>
    {% else %}
      <a href="{% url 'users:register' %}">Register</a> -
      <a href="{% url 'users:login' %}">Login</a>
    {% endif %}
  </p>
  {% block content %}{% endblock content %}
</body>
</html>

Project/project03/19-05/blog/blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}

{% block content %}

    <p>Edit Post</p>

    <form action="{% url 'blogs:edit_post' post.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button name="submit">Save Post</button>
    </form>

{% endblock content %}

Project/project03/19-05/blog/blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block content %}

    <p>Posts</p>

    <a href="{% url 'blogs:new_post' %}">New Post</a>

    <ul>
        {% for post in blog_posts %}
            <li>
                <p>{{ post }}</p>
                <p><a href="{% url 'blogs:edit_post' post.id %}">Edit post</a></p>
            </li>
        {% empty %}
            <li>No posts available.</li>
        {% endfor %}
    </ul>

{% endblock content %}

Project/project03/19-05/blog/blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}

{% block content %}

    <p>New Post</p>

    <form action="{% url 'blogs:new_post' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <br>
        <button name="submit">Add Post</button>
    </form>

{% endblock content %}