Project/project03/18-08/pizzeria/pizzas/urls.py
"""Defines URL patterns for pizzas."""
from django.urls import path
from . import views

app_name = 'pizzas'
urlpatterns = [
    # home page
    path('', views.index, name='index'),
    # display all pizzas
    path('pizzas/', views.pizzas, name='pizzas'),
    # display toppings for a specific pizza
    path('pizzas/<int:pizza_id>', views.pizza, name='pizza'),
]

Project/project03/18-08/pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

Project/project03/18-08/pizzeria/pizzas/models.py
from django.db import models

# Create your models here.


class Pizza(models.Model):
    """Model for a pizza."""
    name = models.CharField(max_length=50)

    def __str__(self):
        return str(self.name)


class Topping(models.Model):
    """Model for a flavor."""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()

    def __str__(self):
        if len(self.name) > 50:
            return f"{self.name[:50]}..."
        else:
            return self.name

Project/project03/18-08/pizzeria/pizzas/views.py
from django.shortcuts import render
from .models import Pizza

# Create your views here.


def index(request):
    # home page for pizzas app
    return render(request, 'pizzas/index.html')


def pizzas(request):
    """Display all pizzas."""
    pizzas = Pizza.objects.order_by('name')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)


def pizza(request, pizza_id):
    """Display toppings for a pizza identified by id."""
    pizza = Pizza.objects.get(id=pizza_id)
    # the default related_name is the 'name_of_your_model' + '_set' => 'topping_set'
    toppings = pizza.topping_set.order_by('name')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

Project/project03/18-08/pizzeria/pizzas/templates/pizzas/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
  <p>
      <a href="{% url 'pizzas:index' %}">Pizzeria</a>
      <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
  </p>
  {% block content %}{% endblock content %}
</body>
</html>

Project/project03/18-08/pizzeria/pizzas/templates/pizzas/index.html
{% extends 'pizzas/base.html' %}
{% block content %}
  <p>Welcome to my Pizzeria.</p>
{% endblock content %}

Project/project03/18-08/pizzeria/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}

  <p>Pizza: {{ pizza }}</p>

  <p>Toppings:</p>
  <ul>
      {% for topping in toppings %}
      <li>{{ topping.name }}</p></li>
      {% empty %}
      <li>No toppings.</li>
      {% endfor %}
  </ul>

{% endblock content %}

Project/project03/18-08/pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %}

{% block content %}
  <p>Pizzas:</p>
  <ul>
      {% for pizza in pizzas %}
        <li>
            <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
        </li>
      {% empty %}
        <li>No pizzas available in catalog.</li>
      {% endfor %}
  </ul>
{% endblock content %}